### ISSUE TITLE
Change police size

### ISSUE THREAD

**Issue by mattx38** [grenagit/MMM-VigilanceMeteoFrance#1]
Hello, 
Good job, the module is a very good idea.
You might be french too, bravo donc, but I will continue in english, for others ;-)

Is it possible to change the police size of the module ?
Directly in the css file ?

Thank you for the work

**Comment by grenagit** [comment]
Thank you for your positive feedback on this module !

I used the default style of the Magic Mirror so that the module fits well next to [Current Weather](https://github.com/MichMich/MagicMirror/tree/master/modules/default/currentweather) or [MMM-MarineWeather](https://github.com/grenagit/MMM-MarineWeather) !

You're right, it's possible to change the font size to CSS by adding a few additional lines to the file `~/MagicMirror/css/custom.css`:
```css 
.MMM-VigilanceMeteoFrance .title {
  /*custom CSS code for title to add here*/
}
.MMM-VigilanceMeteoFrance .description {
  /*custom CSS code for description to add here*/
}
.MMM-VigilanceMeteoFrance .risks {
  /*custom CSS code for risks to add here*/
}
```
*We’ll just have to update the module because I just had to add the `risks` CSS class that was not present before!*
